# This is a basic workflow to help you get started with Actions

name: Log time

# Controls when the workflow will run
on:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test_schedule"
  test_schedule:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Chang Timezone to Taipei
      - name: change timezone
        run: sudo timedatectl set-timezone Asia/Taipei

      - name: show timezone
        run: timedatectl

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: 'action' #action branch

      # Print time
      - name: show time
        run: echo `date`

      # Log time
      - name: log time
        run: echo `date` >> time.log

      - name: Push to master branch
        run: |
          # git config --local user.name wiwari          
          git config --local user.name github-actions
          # git config --local user.email 89345325+wiwari@users.noreply.github.com
          git config --local user.email github-actions@github.com
          git add .
          git commit -m "github action update info by $(date)"
          git push origin action
